#!/usr/bin/env bash
# One-command, terminal-only deploy for PolicyLens. No console login needed.
#
# What it does:
#   1. Packages the Lambda and uploads it to an S3 deploy bucket.
#   2. Deploys the backend CloudFormation stack (Lambda + public Function URL).
#   3. Wires the Function URL into a built copy of the frontend.
#   4. Deploys the frontend to AWS Amplify via a Git-less manual zip deploy.
#
# Prerequisites (one time, in your account):
#   - AWS CLI v2 and a profile with permissions to create CloudFormation stacks,
#     IAM roles, Lambda, S3, and Amplify apps. (The Bedrock-only "policylens"
#     user is NOT enough; use an admin/deployer profile here.)
#   - Amazon Bedrock model access enabled for Nova Micro in the target region.
#
# Usage:
#   scripts/deploy.sh --profile <deployer-profile> [--region us-east-1]
#
set -euo pipefail

PROFILE=""
REGION="us-east-1"
STACK="policylens"
APP_NAME="policylens"
BRANCH="main"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) PROFILE="$2"; shift 2 ;;
    --region)  REGION="$2";  shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$PROFILE" ]]; then
  echo "Error: --profile <deployer-profile> is required." >&2
  echo "Use a profile with deploy permissions, not the Bedrock-only user." >&2
  exit 1
fi

for tool in aws zip curl python3; do
  command -v "$tool" >/dev/null 2>&1 || { echo "Error: $tool not found." >&2; exit 1; }
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
DIST="$REPO_ROOT/dist"
rm -rf "$DIST"; mkdir -p "$DIST"

aws_() { aws --profile "$PROFILE" --region "$REGION" "$@"; }

echo "==> Checking credentials"
ACCOUNT="$(aws_ sts get-caller-identity --query Account --output text)"
echo "    account $ACCOUNT, region $REGION, profile $PROFILE"

# --- 1. Package + upload the Lambda ----------------------------------------
echo "==> Packaging Lambda"
LAMBDA_ZIP="$DIST/policylens-lambda.zip"
( cd "$REPO_ROOT" && zip -qr "$LAMBDA_ZIP" backend -x '*__pycache__*' '*.pyc' )
HASH="$(shasum -a 256 "$LAMBDA_ZIP" | cut -c1-12)"
KEY="lambda/policylens-$HASH.zip"

BUCKET="policylens-deploy-$ACCOUNT-$REGION"
if ! aws_ s3api head-bucket --bucket "$BUCKET" >/dev/null 2>&1; then
  echo "==> Creating deploy bucket $BUCKET"
  if [[ "$REGION" == "us-east-1" ]]; then
    aws_ s3api create-bucket --bucket "$BUCKET" >/dev/null
  else
    aws_ s3api create-bucket --bucket "$BUCKET" \
      --create-bucket-configuration LocationConstraint="$REGION" >/dev/null
  fi
fi
echo "==> Uploading Lambda to s3://$BUCKET/$KEY"
aws_ s3 cp "$LAMBDA_ZIP" "s3://$BUCKET/$KEY" >/dev/null

# --- 2. Deploy the backend stack -------------------------------------------
echo "==> Deploying CloudFormation stack $STACK"
aws_ cloudformation deploy \
  --stack-name "$STACK" \
  --template-file infra/template.yaml \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides LambdaS3Bucket="$BUCKET" LambdaS3Key="$KEY"

API_URL="$(aws_ cloudformation describe-stacks --stack-name "$STACK" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)"
echo "    API URL: $API_URL"

echo "==> Smoke-testing the API URL"
aws_ lambda invoke --function-name policylens /dev/null >/dev/null 2>&1 || true
curl -sf -X POST "$API_URL" -H 'Content-Type: application/json' \
  -d '{"policy":{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"*","Resource":"*"}]}}' \
  >/dev/null && echo "    backend responded OK" || echo "    warning: backend smoke test did not return 200"

# --- 3. Build the frontend with the real API URL ---------------------------
echo "==> Building frontend"
mkdir -p "$DIST/frontend"
cp "$REPO_ROOT"/frontend/* "$DIST/frontend/"
cat > "$DIST/frontend/config.js" <<EOF
// Generated by scripts/deploy.sh — points at the deployed API Gateway URL.
window.POLICYLENS_CONFIG = { API_URL: "$API_URL" };
EOF
FRONTEND_ZIP="$DIST/frontend.zip"
( cd "$DIST/frontend" && zip -qr "$FRONTEND_ZIP" . )

# --- 4. Deploy the frontend to Amplify (Git-less manual deploy) ------------
echo "==> Finding or creating Amplify app"
APP_ID="$(aws_ amplify list-apps --query "apps[?name=='$APP_NAME'].appId | [0]" --output text)"
if [[ "$APP_ID" == "None" || -z "$APP_ID" ]]; then
  APP_ID="$(aws_ amplify create-app --name "$APP_NAME" --query app.appId --output text)"
  echo "    created app $APP_ID"
else
  echo "    using existing app $APP_ID"
fi

if ! aws_ amplify get-branch --app-id "$APP_ID" --branch-name "$BRANCH" >/dev/null 2>&1; then
  aws_ amplify create-branch --app-id "$APP_ID" --branch-name "$BRANCH" >/dev/null
fi

echo "==> Uploading frontend deployment"
DEPLOY_JSON="$(aws_ amplify create-deployment --app-id "$APP_ID" --branch-name "$BRANCH")"
JOB_ID="$(printf '%s' "$DEPLOY_JSON" | python3 -c 'import sys,json;print(json.load(sys.stdin)["jobId"])')"
ZIP_URL="$(printf '%s' "$DEPLOY_JSON" | python3 -c 'import sys,json;print(json.load(sys.stdin)["zipUploadUrl"])')"

curl -sSf -H "Content-Type: application/zip" --upload-file "$FRONTEND_ZIP" "$ZIP_URL"
aws_ amplify start-deployment --app-id "$APP_ID" --branch-name "$BRANCH" --job-id "$JOB_ID" >/dev/null

echo "==> Waiting for Amplify deployment"
while true; do
  STATUS="$(aws_ amplify get-job --app-id "$APP_ID" --branch-name "$BRANCH" \
    --job-id "$JOB_ID" --query 'job.summary.status' --output text)"
  case "$STATUS" in
    SUCCEED) echo "    deployment succeeded"; break ;;
    FAILED|CANCELLED) echo "    deployment $STATUS" >&2; exit 1 ;;
    *) sleep 5 ;;
  esac
done

APP_URL="https://$BRANCH.$APP_ID.amplifyapp.com"
echo
echo "Done."
echo "  App:          $APP_URL"
echo "  API URL:      $API_URL"
echo
echo "Put the app URL in ARTICLE.md and open it in an incognito window to verify."
